language: generic
sudo: required
services:
  -docker
before_install:
  - docker build -t anilmaram/docker-react .

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: $access_key_id
  secret_access_key:
    secure: $secret_access_key
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-774408203811"
  bucket_path: "docker-react"
  on:
    branch: master