language: generic
sudo: required
services:
  -docker
before_install:
  - docker build -t anilmaram/docker-react -f Dockerfile.dev .
scripts:
  - docker run anilmaram/docker-react npm run test -- --coverage